{"level":"error","message":"Failed to restart siegeasbackend: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-08T17:18:26.450Z"}
{"level":"error","message":"Failed to restart siegeasbackend: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-08T17:20:54.543Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-09T07:22:58.611Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-09T07:23:22.407Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-09T07:23:53.432Z"}
{"level":"error","message":"Failed to restart siegedbc: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-09T16:25:38.086Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-17T09:15:44.941Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-17T15:52:19.717Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-17T15:54:27.544Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T10:45:02.877Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T10:57:39.938Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T10:59:05.493Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T10:59:25.062Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T11:02:50.616Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T12:53:03.780Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T12:53:41.917Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T13:00:44.489Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale: Server is not reachable","service":"server-monitor","stack":"Error: Server is not reachable\n    at executeRestart (/app/services/restartService.js:26:17)","timestamp":"2025-09-23T14:01:34.453Z"}
{"level":"error","message":"Failed to restart SiegeAssurnetDigitale.comar.int: hostfile_replace_entries: mkstemp: Read-only file system\r\nupdate_known_hosts: hostfile_replace_entries failed for /root/.ssh/known_hosts: Read-only file system\r\nConnection to 172.30.7.89 closed by remote host.\r\n","service":"server-monitor","stack":"Error: hostfile_replace_entries: mkstemp: Read-only file system\r\nupdate_known_hosts: hostfile_replace_entries failed for /root/.ssh/known_hosts: Read-only file system\r\nConnection to 172.30.7.89 closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-23T14:08:31.863Z"}
{"code":"ESOCKET","command":"CONN","errno":-104,"level":"error","message":"Failed to send alert email: read ECONNRESET","service":"server-monitor","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read","timestamp":"2025-09-23T14:09:14.731Z"}
{"code":"ESOCKET","command":"CONN","errno":-104,"level":"error","message":"Failed to send alert email: read ECONNRESET","service":"server-monitor","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read","timestamp":"2025-09-23T14:18:14.701Z"}
{"code":"ESOCKET","command":"CONN","errno":-104,"level":"error","message":"Failed to send alert email: read ECONNRESET","service":"server-monitor","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read","timestamp":"2025-09-23T15:25:15.113Z"}
{"level":"error","message":"Monitoring error: getaddrinfo EAI_AGAIN database","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"service":"server-monitor","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN database\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-24T12:40:52.595Z"}
{"level":"error","message":"Monitoring error: getaddrinfo EAI_AGAIN database","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"service":"server-monitor","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN database\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-24T15:13:25.059Z"}
{"level":"error","message":"Monitoring error: getaddrinfo EAI_AGAIN database","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"service":"server-monitor","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN database\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-24T15:14:25.055Z"}
{"level":"error","message":"Monitoring error: getaddrinfo EAI_AGAIN database","name":"SequelizeConnectionError","original":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"parent":{"code":"EAI_AGAIN","errno":-3001,"hostname":"database","syscall":"getaddrinfo"},"service":"server-monitor","stack":"SequelizeConnectionError: getaddrinfo EAI_AGAIN database\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-09-24T15:15:25.074Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:16:45.616Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:16:45.741Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:19:31.927Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:19:32.041Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:20:21.379Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0017.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:38:19.988Z 08DDFAC4221EDDFE]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0017.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:38:19.988Z 08DDFAC4221EDDFE]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0017.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:38:19.988Z 08DDFAC4221EDDFE]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T15:38:20.053Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:40:10.719Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:40:10.869Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:40:37.150Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata3.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:40:37.308Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nPermission denied, please try again.\r\nPermission denied, please try again.\r\nroot@recettemigdata1.comar.int: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:41:17.303Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:51:17.251Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T15:51:17.782Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0010.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:19.682Z 08DDFB138750D918]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0010.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:19.682Z 08DDFB138750D918]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0010.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:19.682Z 08DDFB138750D918]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T15:57:19.738Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0014.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:27.653Z 08DDFB14679590F6]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0014.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:27.653Z 08DDFB14679590F6]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0014.ITAP293.PROD.OUTLOOK.COM 2025-09-24T15:57:27.653Z 08DDFB14679590F6]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T15:57:26.140Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:00:42.505Z 08DDFACD19B3951D]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:00:42.505Z 08DDFACD19B3951D]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:00:42.505Z 08DDFACD19B3951D]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T17:00:42.566Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-24T17:11:30.455Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0026.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:38:42.800Z 08DDFB1B010D3A4E]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0026.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:38:42.800Z 08DDFB1B010D3A4E]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0026.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:38:42.800Z 08DDFB1B010D3A4E]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T17:38:42.856Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0001.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:43:42.635Z 08DDFADB4178A00B]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0001.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:43:42.635Z 08DDFADB4178A00B]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0001.ITAP293.PROD.OUTLOOK.COM 2025-09-24T17:43:42.635Z 08DDFADB4178A00B]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-24T17:43:42.690Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZRAP278CA0010.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:03:01.642Z 08DDFB8DD7AF1597]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZRAP278CA0010.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:03:01.642Z 08DDFB8DD7AF1597]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZRAP278CA0010.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:03:01.642Z 08DDFB8DD7AF1597]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T10:03:01.666Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR2P278CA0046.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:54:28.229Z 08DDFBCA9E46611A]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR2P278CA0046.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:54:28.229Z 08DDFBCA9E46611A]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR2P278CA0046.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:54:28.229Z 08DDFBCA9E46611A]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T10:54:28.954Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0097.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:57:24.327Z 08DDFAD9096915BF]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0097.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:57:24.327Z 08DDFAD9096915BF]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0097.CHEP278.PROD.OUTLOOK.COM 2025-09-25T10:57:24.327Z 08DDFAD9096915BF]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T10:57:24.355Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0029.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:51:20.931Z 08DDFBD0F27E9A89]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0029.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:51:20.931Z 08DDFBD0F27E9A89]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI1P293CA0029.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:51:20.931Z 08DDFBD0F27E9A89]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T14:51:21.641Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0004.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:55:03.801Z 08DDFBDCC17E8AD1]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0004.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:55:03.801Z 08DDFBDCC17E8AD1]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0004.ITAP293.PROD.OUTLOOK.COM 2025-09-25T14:55:03.801Z 08DDFBDCC17E8AD1]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T14:55:04.498Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Erreur lors de l'envoi de l'email de test: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0178.CHEP278.PROD.OUTLOOK.COM 2025-09-25T14:55:52.828Z 08DDFAC3B12DAF10]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0178.CHEP278.PROD.OUTLOOK.COM 2025-09-25T14:55:52.828Z 08DDFAC3B12DAF10]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [ZR0P278CA0178.CHEP278.PROD.OUTLOOK.COM 2025-09-25T14:55:52.828Z 08DDFAC3B12DAF10]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T14:55:52.842Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0008.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:40:38.320Z 08DDFBBCF0A369AD]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0008.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:40:38.320Z 08DDFBBCF0A369AD]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0008.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:40:38.320Z 08DDFBBCF0A369AD]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T16:40:40.137Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0003.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:41:20.034Z 08DDFC0E552BD19E]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0003.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:41:20.034Z 08DDFC0E552BD19E]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI0P293CA0003.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:41:20.034Z 08DDFC0E552BD19E]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T16:41:20.410Z"}
{"code":"EAUTH","command":"AUTH LOGIN","level":"error","message":"Failed to send alert email: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI2P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:43:47.648Z 08DDFBFCA7F3FBAB]","response":"535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI2P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:43:47.648Z 08DDFBFCA7F3FBAB]","responseCode":535,"service":"server-monitor","stack":"Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [MI2P293CA0006.ITAP293.PROD.OUTLOOK.COM 2025-09-25T16:43:47.648Z 08DDFBFCA7F3FBAB]\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:809:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1588:34)\n    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1542:18)\n    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:993:20)\n    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:774:14)\n    at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)\n    at TLSSocket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Readable.push (node:internal/streams/readable:278:10)","timestamp":"2025-09-25T16:43:47.389Z"}
{"code":"ESOCKET","command":"CONN","errno":-104,"level":"error","message":"Failed to send alert email: read ECONNRESET","service":"server-monitor","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read","timestamp":"2025-09-26T10:18:16.132Z"}
{"code":"ESOCKET","command":"CONN","errno":-104,"level":"error","message":"Failed to send alert email: read ECONNRESET","service":"server-monitor","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read","timestamp":"2025-09-26T10:21:57.662Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-09-26T13:13:01.956Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:14:01.797Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:15:01.791Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:16:01.814Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:17:01.822Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:18:01.818Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:19:01.829Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:20:01.839Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:21:01.861Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:22:01.881Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:23:01.851Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:23:57.083Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:24:56.881Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:25:56.931Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:26:56.908Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:27:56.931Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:28:56.896Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:29:56.915Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:30:56.912Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:33:52.058Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:34:51.901Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:35:52.037Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:36:52.105Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:37:51.956Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:38:51.966Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:39:51.997Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:40:51.985Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:41:51.972Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:42:51.973Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:43:51.978Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:44:51.976Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:47:56.430Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T13:48:56.248Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T14:34:56.621Z"}
{"level":"error","message":"Monitoring error: sendAlertMail is not defined","service":"server-monitor","stack":"ReferenceError: sendAlertMail is not defined\n    at monitorAllServers (/app/services/monitoring.js:60:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Timeout._onTimeout (/app/services/monitoring.js:13:5)","timestamp":"2025-09-26T14:36:01.490Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:10:00.577Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:10:01.147Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:33:00.728Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:33:01.194Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:41:01.882Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:41:02.430Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:44:03.498Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-26T15:47:02.250Z"}
{"level":"error","message":"Failed to restart RecetteMigData1: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata1.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-29T07:45:05.951Z"}
{"level":"error","message":"Failed to restart RecetteMigData3: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n","service":"server-monitor","stack":"Error: Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).\r\nConnection to recettemigdata3.comar.int closed by remote host.\r\n\n    at ChildProcess.<anonymous> (/app/services/restartService.js:130:16)\n    at ChildProcess.emit (node:events:517:28)\n    at maybeClose (node:internal/child_process:1098:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:303:5)","timestamp":"2025-09-29T07:45:08.495Z"}
